# Project
version=3.0
group=net.darkhax.shieldbannerfix

# Common
minecraft_version=1.19.2

# Forge
forge_version=43.1.1

# Fabric
fabric_version=0.60.0+1.19.2
fabric_loader_version=0.14.9

# Mod options
mod_name=ShieldBannerFix
mod_author=Darkhax
mod_id=shieldbannerfix
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/shield-banner-fix
mod_source=https://github.com/Darkhax-Minecraft/Shield-Banner-Fix
mod_issues=https://github.com/Darkhax-Minecraft/Shield-Banner-Fix/issues
mod_description=Fixes shields with banners not rendering designs accurately. 
mod_license=ARR
mod_twitter=https://twitter.com/DarkhaxDev
mod_discord=https://discord.darkhax.net

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# CurseForgeGradle
curse_project=967792